### ISSUE TITLE
Support for decrypting KMS encrypted env files from S3 

### ISSUE THREAD

**Issue by danielwhatmuff** [Miserlou/Zappa#514] opened 2016-12-03 23:35 UTC
Would be great to be able to encrypt environment files using KMS, upload them to S3 and then have the lambda function decrypt them using an IAM policy. Currently they will be stored in plain text and available to anyone with S3 access. 

So you would specify a KMS CMK ID in the Zappa config and a local env file to be encrypted, then when running zappa deploy it encrypts and uploads the env file and adds IAM decrypt policy to the lambda function.

Workflow a bit like this - https://github.com/UKHomeOffice/s3secrets

**Comment by Miserlou** [comment] 2016-12-05 20:18
This is, in essence, a duplicate of: https://github.com/Miserlou/Zappa/issues/501

I think if you're using S3 env vars for that purpose, you probably want to handle that description at the application layer, so you're not further locked in. It sounds like you want what #501 will offer anyway.

**Comment by Miserlou** [comment] 2017-05-08 17:58
Fixed by AWS KMS Env Vars.

**Closed by Miserlou** 2017-05-08 17:58 UTC
Labels: duplicate

**Comment by m90** [comment] 2020-05-26 08:04
> Fixed by AWS KMS Env Vars.

How does this actually work? From reading the docs it seems to me as if I could put a JSON file structured like this on S3 and refer to it as `remote_env` when specifying a `aws_kms_key_arn`:

```json
{
  "MY_SECRET_THING": "<ENCRYPTED_VALUE>"
}
```
but somehow the Lambda will use the encrypted value instead.
