### ISSUE TITLE
`exclude` setting is not working as expected.

### ISSUE THREAD

**Issue by jnoortheen** [Miserlou/Zappa#1343] opened 2018-01-07 15:32 UTC
## Context
Upon packaging a project, the exclude setting is not working. For example, by default the code will exclude **'__pycache__/*'** from final zip package. But this is not happening. I could see `__pycache__` in the final package. 

As I inspected the code, the implementation of `zappa.utilities.copytree` should be enhanced. For the above example, if we define it as **__pycache__** (without the slash at the end) it will work. 

## Expected Behavior
**__pycache__** folder should not be in the package

## Actual Behavior
__pycache__ is not excluded

## Possible Fix
instead of checking file names [after os.listdir the directory path is stripped] , we should check the glob pattern of the full path of the file

## Steps to Reproduce

1.
2.
3.

## Your Environment

* Zappa version used: 0.45.1
* Operating System and Python version: 3.6.4
* The output of `pip freeze`: 
* Your `zappa_settings.py`:

**Comment by scoates** [comment] 2018-02-04 02:30
Related, probably #692

**Comment by scoates** [comment] 2018-02-23 19:52
Please reopen if this is not a duplicate of #692.

**Closed by scoates** 2018-02-23 19:52 UTC
Labels: duplicate
