### ISSUE TITLE
Crash when lambda function doesn't exist while creating API gateway routes

### ISSUE THREAD

**Issue by josephquigley** [Miserlou/Zappa#304] opened 2016-09-06 01:14 UTC
EDIT: I realized that I've been calling "deploy" this whole time when trying to update my app. But I'll leave this open in case this is a non-happy path bug that is worth fixing.

I've been experiencing a lot of difficulty getting my IAM permissions set up properly for my zappa user. After creating the endpoints it errored out when zappa tried to run a patch operation for a "/stage/" url.

I fixed the issue by wildcarding the entire endpoint and reran the deploy. This caused zappa to error out saying the lambda function already existed. I deleted it and re-ran then encountered the following error: "UnboundLocalError: local variable 'response' referenced before assignment".

The gateway was created during a previous launch, but it may not have been fully set up.

    (venv) Josephs-iMac:TestApp wash $ zappa deploy dev
    Packaging project as zip...
    Uploading zip (9.8MiB)...
    100%
    Function does not exist, please deploy first. Ex: zappa deploy dev.
    Creating API Gateway routes (this only happens once)..
    Oh no! An error occured! :(

    Traceback (most recent call last):
      File "/Library/Python/2.7/site-packages/zappa/cli.py", line 1189, in handle
        sys.exit(cli.handle())
      File "/Library/Python/2.7/site-packages/zappa/cli.py", line 177, in handle
        self.deploy()
      File "/Library/Python/2.7/site-packages/zappa/cli.py", line 274, in deploy
        self.lambda_arn, self.lambda_name, self.api_key_required, self.integration_content_type_aliases)
      File "/Library/Python/2.7/site-packages/zappa/zappa.py", line 685, in create_api_gateway_routes
        api_id = response['id']
    UnboundLocalError: local variable 'response' referenced before assignment

**Comment by Miserlou** [comment] 2016-09-06 02:15
Unhappy code path! Good bug! :D

**Comment by Miserlou** [comment] 2016-09-06 17:07
I'm actually unable to reproduce this, what version of Zappa are you using? 

On mine, I get: 

    $ zappa update
    This application is already deployed - did you mean to call update?

¯\_(ツ)_/¯

**Comment by Miserlou** [comment] 2016-09-06 17:09
>  Miserlou authored 26 days ago 

:)

**Comment by Miserlou** [comment] 2016-09-07 21:10
Gonna close this, feel free to reopen if it's not fixed.

**Closed by Miserlou** 2016-09-07 21:10 UTC
