### ISSUE TITLE
Import Error: task.urls

### ISSUE THREAD

**Issue by pjodouin** [Miserlou/Zappa#164] opened 2016-07-02 14:49 UTC
Hi, just starting with Zappa (cool project by the way!) 

Not sure if this is Zappa or Mezzanine as the traceback is not very helpful.  Mezzanine works fine locally using RDS but after deploying to Lambda I get the following:

```
Traceback:

File "/usr/lib64/python2.7/importlib/__init__.py" in import_module
  37.     __import__(name)

Exception Type: ImportError at /
Exception Value: No module named task.urls

```

Any ideas what this could be?

Thanks!
Pierre

**Comment by Miserlou** [comment] 2016-07-03 03:00
Hi Pierre!

I've used Zappa with Mezzanine before (if I recall correctly), but I didn't do a very good job of documenting the steps. This seems like a good time to do that.

Can you post a little more information: Your python version, your requirements.txt, your zappa_settings file? The lib64 shit is new, I hope that's not a bug, but it very much could be.

**Comment by pjodouin** [comment] 2016-07-03 17:14
Hi Rick,

I wasn't sure if this was a Mezzanine or Zappa issue which is why I didn't post more info but here's what I've got:

`Python 2.7.10`

pip freeze from virtual env
```
base58==0.2.2
beautifulsoup4==4.1.3
bleach==1.4.3
boto3==1.3.1
botocore==1.4.13
chardet==2.3.0
Django==1.9.7
django-contrib-comments==1.7.1
django-zappa==0.13.1
docopt==0.6.2
docutils==0.12
filebrowser-safe==0.4.3
future==0.9.0
futures==3.0.5
grappelli-safe==0.4.2
hjson==1.5.4
html5lib==0.9999999
jmespath==0.9.0
lambda-packages==0.5.0
Mezzanine==4.1.0
mysql-connector-python-rf==2.1.3
MySQL-python==1.2.5
oauthlib==1.1.2
Pillow==3.3.0
python-dateutil==2.5.3
python-slugify==1.2.0
pytz==2016.4
requests==2.10.0
requests-oauthlib==0.6.1
six==1.10.0
tqdm==4.4.1
tzlocal==1.0
Unidecode==0.4.19
Werkzeug==0.11.8
wheel==0.29.0
wsgi-request-logger==0.4.5
zappa==0.17.4

```

```
ZAPPA_SETTINGS = {
    'production': {
       's3_bucket': 'ivcs-package',
       'settings_file': 's3://ivcs-package:prod/settings.py',
    },
    'dev': {
       's3_bucket': 'ivcs-package',
       'settings_file': '~/PyCharmProjects/ivcs_cms/ivcs_cms/settings.py',
    },
}

```

Mezzanine requirements.txt

`Mezzanine==4.1.0`


I'm working with **dev**.

Let me know if there's anything you need or anything else I can try.  I just wish the traceback was a little more helpful.

Thanks!!

**Comment by Miserlou** [comment] 2016-07-12 17:45
Wow, so it turned out the dev branch was a few hundred commits behind master. :( That makes this harder to resolve. Can you try again now?

**Comment by pjodouin** [comment] 2016-07-23 14:47
Hi Rich,

I just realized I should have posted this in django-zappa -- sorry.

But I'm getting the same error.   I managed to get a better traceback with "manage tail" -- nice feature by the way!

```
[1467420137174] [ERROR]	2016-07-02T00:42:17.158Z	d1ebcfc3-3fed-11e6-a762-3d531a9a6004	Internal Server Error: /dev/
Traceback (most recent call last):
  File "/private/var/folders/jt/jn65b8mx7c7694wn_3lybt_00000gp/T/pip-build-GyIQPH/django/django/core/handlers/base.py", line 134, in get_response
  File "/private/var/folders/jt/jn65b8mx7c7694wn_3lybt_00000gp/T/pip-build-GyIQPH/django/django/core/urlresolvers.py", line 374, in resolve
  File "/private/var/folders/jt/jn65b8mx7c7694wn_3lybt_00000gp/T/pip-build-GyIQPH/django/django/utils/functional.py", line 33, in __get__
  File "/private/var/folders/jt/jn65b8mx7c7694wn_3lybt_00000gp/T/pip-build-GyIQPH/django/django/core/urlresolvers.py", line 417, in url_patterns
  File "/private/var/folders/jt/jn65b8mx7c7694wn_3lybt_00000gp/T/pip-build-GyIQPH/django/django/utils/functional.py", line 33, in __get__
  File "/private/var/folders/jt/jn65b8mx7c7694wn_3lybt_00000gp/T/pip-build-GyIQPH/django/django/core/urlresolvers.py", line 410, in urlconf_module
  File "/usr/lib64/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named task.urls
```

I can move this issue to django-zappa if you like.

Thanks!

**Comment by Miserlou** [comment] 2016-09-14 18:02
Closing. Will reopen if somebody can confirm this is latest.

**Closed by Miserlou** 2016-09-14 18:02 UTC

**Comment by jjorissen52** [comment] 2017-12-06 01:42
I encountered the same issue and created another issue. I ended up resolving it: https://github.com/Miserlou/Zappa/issues/1245
