### ISSUE TITLE
'Zappa update dev' results in 'Operation not permitted' error

### ISSUE THREAD

**Issue by dtenenba** [Miserlou/Zappa#729] opened 2017-03-21 15:31 UTC
## Context

When I do `zappa update dev` I get an error.

 

## Expected Behavior

No error.

Successful update.

## Actual Behavior

```
Calling update for environment dev..
Oh no! An error occurred! :(

==============

Traceback (most recent call last):
  File "/Users/dtenenba/envs/gems/lib/python2.7/site-packages/zappa/cli.py", line 2165, in handle
    sys.exit(cli.handle())
  File "/Users/dtenenba/envs/gems/lib/python2.7/site-packages/zappa/cli.py", line 414, in handle
    self.dispatch_command(self.command, environment)
  File "/Users/dtenenba/envs/gems/lib/python2.7/site-packages/zappa/cli.py", line 450, in dispatch_command
    self.update()
  File "/Users/dtenenba/envs/gems/lib/python2.7/site-packages/zappa/cli.py", line 703, in update
    self.create_package()
  File "/Users/dtenenba/envs/gems/lib/python2.7/site-packages/zappa/cli.py", line 1774, in create_package
    ["boto3", "dateutil", "botocore", "s3transfer", "six.py", "jmespath", "concurrent"])
  File "/Users/dtenenba/envs/gems/lib/python2.7/site-packages/zappa/zappa.py", line 391, in create_lambda_zip
    copytree(cwd, temp_project_path, symlinks=False, ignore=shutil.ignore_patterns(*excludes))
  File "/Users/dtenenba/envs/gems/lib/python2.7/site-packages/zappa/util.py", line 48, in copytree
    copytree(s, d, symlinks, ignore)
  File "/Users/dtenenba/envs/gems/lib/python2.7/site-packages/zappa/util.py", line 48, in copytree
    copytree(s, d, symlinks, ignore)
  File "/Users/dtenenba/envs/gems/lib/python2.7/site-packages/zappa/util.py", line 48, in copytree
    copytree(s, d, symlinks, ignore)
  File "/Users/dtenenba/envs/gems/lib/python2.7/site-packages/zappa/util.py", line 26, in copytree
    shutil.copystat(src, dst)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 103, in copystat
    os.chflags(dst, st.st_flags)
OSError: [Errno 1] Operation not permitted: '/var/folders/dt/7452mw1s5rn1tqk60l8y4hdc0000gn/T/1490110056/env/include/python2.7'

==============

Need help? Found a bug? Let us know! :D
File bug reports on GitHub here: https://github.com/Miserlou/Zappa
And join our Slack channel here: https://slack.zappa.io
Love!,
 ~ Team Zappa!
```

## Possible Fix

Dunno.

## Steps to Reproduce

1.
2.
3.

## Your Environment

* Zappa version used: 0.39.1
* Operating System and Python version: OS X 10.12.1, Python 2.7.10
* Link to your project (optional):
* Your `zappa_settings.py`: 
You mean `zappa_settings.json`? Here it is:

```
{
    "dev": {
        "s3_bucket": "zappa-deployment-dev",
        "app_function": "my_app.app",
        "keep_warm": false,
        "role_name": "LambdaCustomRole",
        "remote_env_bucket": "gems-trigger-remote-env-dev",
        "remote_env_file": "config.json",
        "aws_region": "us-west-2"
    }
}
```

**Comment by Miserlou** [comment] 2017-03-21 15:35
Duplicate of https://github.com/Miserlou/Zappa/issues/729 - please move discussion there.

**Comment by Miserlou** [comment] 2017-03-21 15:36
Oops, this is the link: https://github.com/Miserlou/Zappa/issues/720

**Closed by Miserlou** 2017-03-21 15:35 UTC
