### ISSUE TITLE
KeyError: 'pip._vendor.urllib3.contrib'

### ISSUE THREAD

**Issue by oxbits** [Miserlou/Zappa#1447] opened 2018-03-18 12:51 UTC
$ zappa deploy
Calling deploy for stage dev..
Oh no! An error occurred! :(

==============

Traceback (most recent call last):
  File "/Users/ox/.local/share/virtualenvs/ox-zje1HLlw/lib/python3.6/site-packages/zappa/cli.py", line 2610, in handle
    sys.exit(cli.handle())
  File "/Users/ox/.local/share/virtualenvs/ox-zje1HLlw/lib/python3.6/site-packages/zappa/cli.py", line 505, in handle
    self.dispatch_command(self.command, stage)
  File "/Users/ox/.local/share/virtualenvs/ox-zje1HLlw/lib/python3.6/site-packages/zappa/cli.py", line 539, in dispatch_command
    self.deploy(self.vargs['zip'])
  File "/Users/ox/.local/share/virtualenvs/ox-zje1HLlw/lib/python3.6/site-packages/zappa/cli.py", line 709, in deploy
    self.create_package()
  File "/Users/ox/.local/share/virtualenvs/ox-zje1HLlw/lib/python3.6/site-packages/zappa/cli.py", line 2171, in create_package
    disable_progress=self.disable_progress
  File "/Users/ox/.local/share/virtualenvs/ox-zje1HLlw/lib/python3.6/site-packages/zappa/core.py", line 447, in create_lambda_zip
    import pip
  File "/Users/ox/.local/share/virtualenvs/ox-zje1HLlw/lib/python3.6/site-packages/pip/__init__.py", line 45, in <module>
    from pip.vcs import git, mercurial, subversion, bazaar  # noqa
  File "/Users/ox/.local/share/virtualenvs/ox-zje1HLlw/lib/python3.6/site-packages/pip/vcs/mercurial.py", line 9, in <module>
    from pip.download import path_to_url
  File "/Users/ox/.local/share/virtualenvs/ox-zje1HLlw/lib/python3.6/site-packages/pip/download.py", line 40, in <module>
    from pip._vendor import requests, six
  File "/Users/ox/.local/share/virtualenvs/ox-zje1HLlw/lib/python3.6/site-packages/pip/_vendor/requests/__init__.py", line 98, in <module>
    from . import packages
  File "/Users/ox/.local/share/virtualenvs/ox-zje1HLlw/lib/python3.6/site-packages/pip/_vendor/requests/packages.py", line 12, in <module>
    sys.modules['pip._vendor.requests.packages.' + mod] = sys.modules["pip._vendor." + mod]
KeyError: 'pip._vendor.urllib3.contrib'

####

settings:

{
    "dev": {
        "app_function": "hello.app",
        "aws_region": null,
        "profile_name": null,
        "project_name": "zappa-hey-yo",
        "runtime": "python3.6",
        "s3_bucket": "zappa-hwydhsa7d"
    }

**Comment by suriya** [comment] 2018-03-18 14:32
I was about to post this same issue in order to help others. After debugging for a while, I found that this is happening because of pip version 9.0.2, released 3 days ago (March 16, 2018).

If any one else is facing the same issue, downgrade to  pip version 9.0.1 `pip install pip==9.0.1` and Zappa will work as usual.

**Comment by suriya** [comment] 2018-03-18 14:35
Duplicate of #1446

**Comment by oxbits** [comment] 2018-03-18 14:51
Nice work @suriya, thank you!

**Comment by rhyspowell** [comment] 2018-03-18 16:57
thank you, was just about to start debugging!

**Comment by Miserlou** [comment] 2018-03-18 18:49
Closing duplicate. Track upstream here: https://github.com/pypa/pip/issues/5081

**Closed by Miserlou** 2018-03-18 18:49 UTC
Labels: duplicate

**Comment by LaundroMat** [comment] 2018-03-19 20:28
For people on Windows in a virtualenv, downgrading won't work (you'll uninstall pip and then won't be able to reinstall the older version).

The solution is to uninstall pip (`pip uninstall pip`), then get the `get-pip.py` installation script [from the pip docs](https://pip.pypa.io/en/stable/installing/#installing-with-get-pip-py) and then do `python get-pip.py pip==9.0.1`

**Comment by zhaovianet** [comment] 2018-03-21 12:06
Thank you sooo much, but why?
