### ISSUE TITLE
Support for SSL certificates that aren't from Let's Encrypt!

### ISSUE THREAD

**Issue by adimarco** [Miserlou/Zappa#517] opened 2016-12-05 20:17 UTC
I have my own SSL certificate, and DNS handled by Cloudflare.  I want to point a custom domain to my code that's deployed with Zappa, but I don't want to generate a new SSL cert with Let's Encrypt! or use route53 for my custom domain

Is it possible to use Zappa with my existing cert/dns provider instead of going through the Let's Encrypt! / route53 process that's documented?

**Comment by Miserlou** [comment] 2016-12-05 20:20
Duplicate of #401.

This should be easy to do (and would be useful for me as well), but isn't implemented yet. PRs welcome!

**Comment by bcongdon** [comment] 2017-02-06 16:21
I'd be interested in working on this.

I think a likely solution would to programmatically create/manage a [custom domain](https://docs.aws.amazon.com/apigateway/latest/developerguide/how-to-custom-domains.html#how-to-custom-domains-console) name in API gateway (with your existing cert), and have that map to the Zappa-created API. The path to your cert file could be kept in your `zappa_settings.json`.

Does that sound reasonable?

**Comment by Miserlou** [comment] 2017-02-06 16:24
Most of that code is there already (although it could do with a serious refactor/test), the main difference here is that we supply the `certificate_file`, `certificate_secret` and `certificate_chain` from the settings, not generated by acme-tiny

**Comment by Miserlou** [comment] 2017-03-06 19:32
Fix

**Closed by Miserlou** 2017-03-06 19:32 UTC
Labels: duplicate, enhancement, help wanted
