### ISSUE TITLE
Is it possible to deploy a zappa app on a Specific API gateway resource instead of "/"?

### ISSUE THREAD

**Issue by kyeljmd** [Miserlou/Zappa#1454] opened 2018-03-22 23:56 UTC
Is it possible to deploy a zappa app on a Specific API gateway resource? I have multiple flask apps that are existing and I want all of them be deployed on a same API Gateway but deployed on different lambdas. Is it possible to deploy a specific flask application powered by zappa to be deployed on a specific api gateway resource? i have noticed that the fault mapping is always at the root "/" however, I want some of my flask apps/endpoints to be deployed on "/somePath".

**Comment by madeddie** [comment] 2018-06-21 20:20
@kyeljmd #1504 should fix this for you, can you check?

**Comment by mcrowson** [comment] 2018-09-24 13:32
Closing as dupe of #1504.

**Closed by mcrowson** 2018-09-24 13:32 UTC
