### ISSUE TITLE
zappa trying to deploy API gateway when use_apigateway = false

### ISSUE THREAD

**Issue by westcool10** [Miserlou/Zappa#493] opened 2016-11-25 12:01 UTC
Hi there, 

I encountered an error while trying to update my lambda with zappa 0.28.3. The error was from API deployment even though I set use_apigateway = false in zappa_settings. FYI I didn't have this issue with 0.28.2. Here's the command output snippet:

...
CloudFormation stack missing, re-deploy to enable updates
ERROR:Could not get API ID.
Traceback (most recent call last):
  File "/Users/moonk/Work/ScoopHipsterBot/parts/zappa/lib/python2.7/site-packages/zappa/zappa.py", line 1232, in get_api_id
    LogicalResourceId='Api')
  File "/Users/moonk/Work/ScoopHipsterBot/parts/zappa/lib/python2.7/site-packages/botocore/client.py", line 251, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/Users/moonk/Work/ScoopHipsterBot/parts/zappa/lib/python2.7/site-packages/botocore/client.py", line 537, in _make_api_call
    raise ClientError(parsed_response, operation_name)
ClientError: An error occurred (ValidationError) when calling the DescribeStackResource operation: Stack 'scoop-hipster-beta' does not exist
Deploying API Gateway..
Oh no! An error occurred! :(

==============

Traceback (most recent call last):
  File "/Users/moonk/Work/ScoopHipsterBot/parts/zappa/lib/python2.7/site-packages/zappa/cli.py", line 1654, in handle
    sys.exit(cli.handle())
  File "/Users/moonk/Work/ScoopHipsterBot/parts/zappa/lib/python2.7/site-packages/zappa/cli.py", line 247, in handle
    self.dispatch_command(self.command, environment)
  File "/Users/moonk/Work/ScoopHipsterBot/parts/zappa/lib/python2.7/site-packages/zappa/cli.py", line 281, in dispatch_command
    self.update()
  File "/Users/moonk/Work/ScoopHipsterBot/parts/zappa/lib/python2.7/site-packages/zappa/cli.py", line 508, in update
    endpoint_url = self.deploy_api_gateway(api_id)
  File "/Users/moonk/Work/ScoopHipsterBot/parts/zappa/lib/python2.7/site-packages/zappa/cli.py", line 1623, in deploy_api_gateway
    cloudwatch_metrics_enabled=self.zappa_settings[self.api_stage].get('cloudwatch_metrics_enabled', False),
  File "/Users/moonk/Work/ScoopHipsterBot/parts/zappa/lib/python2.7/site-packages/zappa/zappa.py", line 918, in deploy_api_gateway
    variables=variables or {}
  File "/Users/moonk/Work/ScoopHipsterBot/parts/zappa/lib/python2.7/site-packages/botocore/client.py", line 251, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/Users/moonk/Work/ScoopHipsterBot/parts/zappa/lib/python2.7/site-packages/botocore/client.py", line 513, in _make_api_call
    api_params, operation_model, context=request_context)
  File "/Users/moonk/Work/ScoopHipsterBot/parts/zappa/lib/python2.7/site-packages/botocore/client.py", line 566, in _convert_to_request_dict
    api_params, operation_model)
  File "/Users/moonk/Work/ScoopHipsterBot/parts/zappa/lib/python2.7/site-packages/botocore/validate.py", line 270, in serialize_to_request
    raise ParamValidationError(report=report.generate_report())
ParamValidationError: Parameter validation failed:
Invalid type for parameter restApiId, value: None, type: <type 'NoneType'>, valid types: <type 'basestring'>

==============

Need help? Found a bug? Let us know! :D
File bug reports on GitHub here: https://github.com/Miserlou/Zappa
And join our Slack channel here: https://slack.zappa.io
Love!,
 ~ Team Zappa!

**Comment by Miserlou** [comment] 2016-11-25 12:34
`use_apigateway` has been moved to `apigateway_enabled`. It was supposed to be backwards-compatible but I guess it isn't.. hold on..

**Comment by Miserlou** [comment] 2016-11-25 13:22
Fixed in 0.30.1

**Closed by Miserlou** 2016-11-25 13:22 UTC

**Comment by westcool10** [comment] 2016-11-26 04:49
Thank you for the fix!

**Comment by ninthcoast** [comment] 2017-02-05 18:56
I am getting the same error:

    raise ParamValidationError(report=report.generate_report())
ParamValidationError: Parameter validation failed:
Invalid type for parameter restApiId, value: None, type: <type 'NoneType'>, valid types: <type 'basestring'>

**Comment by Miserlou** [comment] 2017-02-05 19:01
Where is that? I need more info, Zappa version, your settings, etc. See the new issue template for what I need to debug that.

**Comment by ninthcoast** [comment] 2017-02-05 19:36
## Context

 

## Expected Behavior


## Actual Behavior


## Possible Fix


## Steps to Reproduce


1.
2.
3.
4.

## Context


I am going through this tutorial...
https://gun.io/blog/serverless-microservices-with-zappa-and-flask/
and have gotten to the point where I deploy to AWS and when I- (env)[Derek]$ zappa update dev
I get this error...

CloudFormation stack missing, re-deploy to enable updates
Deploying API Gateway..
Oh no! An error occurred! :(

==============

Traceback (most recent call last):
  File "/Users/derekstock/Desktop/FlaskZappa/env/lib/python2.7/site-packages/zappa/cli.py", line 2057, in handle
    sys.exit(cli.handle())
  File "/Users/derekstock/Desktop/FlaskZappa/env/lib/python2.7/site-packages/zappa/cli.py", line 399, in handle
    self.dispatch_command(self.command, environment)
  File "/Users/derekstock/Desktop/FlaskZappa/env/lib/python2.7/site-packages/zappa/cli.py", line 435, in dispatch_command
    self.update()
  File "/Users/derekstock/Desktop/FlaskZappa/env/lib/python2.7/site-packages/zappa/cli.py", line 725, in update
    endpoint_url = self.deploy_api_gateway(api_id)
  File "/Users/derekstock/Desktop/FlaskZappa/env/lib/python2.7/site-packages/zappa/cli.py", line 2026, in deploy_api_gateway
    cloudwatch_metrics_enabled=self.zappa_settings[self.api_stage].get('cloudwatch_metrics_enabled', False),
  File "/Users/derekstock/Desktop/FlaskZappa/env/lib/python2.7/site-packages/zappa/zappa.py", line 1122, in deploy_api_gateway
    variables=variables or {}
  File "/Users/derekstock/Desktop/FlaskZappa/env/lib/python2.7/site-packages/botocore/client.py", line 253, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/Users/derekstock/Desktop/FlaskZappa/env/lib/python2.7/site-packages/botocore/client.py", line 517, in _make_api_call
    api_params, operation_model, context=request_context)
  File "/Users/derekstock/Desktop/FlaskZappa/env/lib/python2.7/site-packages/botocore/client.py", line 572, in _convert_to_request_dict
    api_params, operation_model)
  File "/Users/derekstock/Desktop/FlaskZappa/env/lib/python2.7/site-packages/botocore/validate.py", line 270, in serialize_to_request
    raise ParamValidationError(report=report.generate_report())
ParamValidationError: Parameter validation failed:
Invalid type for parameter restApiId, value: None, type: <type 'NoneType'>, valid types: <type 'basestring'>


## Your Environment

* Zappa version used: I and using $pip install zappa in a virtualenv
* Operating System and Python version: python 2.7.10, Mac OSX Sierra 10.12.3
* Link to your project (optional):
* Your `zappa_settings.py`: 
{
    "dev": {
        "s3_bucket": "blueeyespy-ms",
        "app_function": "my_app.app",
        "apigateway_enabled": false"
    }
}
true or false makes no difference... I only added apigateway_enabled because of the previous commentor.

**Comment by mp3il** [comment] 2017-02-05 19:52
@ninthcoast Derek, please run
`pip list | grep zappa ` in your terminal so we'll know which version of zappa your'e using :)

**Comment by ninthcoast** [comment] 2017-02-05 19:53
zappa (0.35.1)

**Comment by mp3il** [comment] 2017-02-05 19:54
Ok, I just noticed that you are using zappa_settings.py instead of zappa_settings.**json**, is that really the case?

**Comment by ninthcoast** [comment] 2017-02-05 19:55
zappa_settings.json as the tutorial shows

**Comment by mp3il** [comment] 2017-02-05 19:58
Ok, I think I found that
your json is wrong, look at the value of apigateway_enabled

it should be true or false. not false", not "false", and not "true" :)

try using this as the content of your settings file:
```
{
	"dev": {
	"s3_bucket": "blueeyespy-ms",
	"app_function": "my_app.app",
	"apigateway_enabled": false
	}
}
```

**Comment by mp3il** [comment] 2017-02-05 19:59
Anyway, to make it easier - if you could join the slack channel, I would love to try and help you debug it and find the problem :)

**Comment by ninthcoast** [comment] 2017-02-05 20:02
fixed!! thank you! It was the json.... :)

**Comment by ninthcoast** [comment] 2017-02-05 20:34
hmm having the same error if I set the apigateway_enabled to true... I moved to slack
