### ISSUE TITLE
Problem with running function upon S3 event after updating Zappa

### ISSUE THREAD

**Issue by slacis** [Miserlou/Zappa#491] opened 2016-11-24 06:10 UTC
In my Zappa project I have written simple function to write an entry into a DynamoDB table every time a file is uploaded to S3. Until Zappa version 0.26, this function worked without any issues. However, after updating zappa to the latest version (0.29.1) and redeploying, the function no longer works. As a side node, the function works without problems when deployed as a regular lambda (separate from zappa). The event and the error that I am getting in 'zappa tail' is as follows: 

> [1479966175270] Zappa Event: {u'Records': [{u'eventVersion': u'2.0', u'eventTime': u'2016-11-24T05:42:54.854Z', u'requestParameters': {u'sourceIPAddress': u'172.30.80.239'}, u's3': {u'configurationId': u'arn:aws:lambda:ap-northeast-1:329458738510:function:campi-dev', u'object': {u'eTag': u'4fd03030982334998dc4337e631d4bf9', u'sequencer': u'0058367DDE9C55BDA0', u'key': u'**CHANGEDFORPRIVACY**', u'size': 173649}, u'bucket': {u'arn': u'arn:aws:s3:::**CHANGEDFORPRIVACY**', u'name': u'**CHANGEDFORPRIVACY**', u'ownerIdentity': {u'principalId': u'A3NDLAT5L1NQI5'}}, u's3SchemaVersion': u'1.0'}, u'responseElements': {u'x-amz-id-2': u'r1htvp+ZjqT09kLAb+AO8H7gllf+4KpnNp/HLyxKwqEFQ+QvswHupuJtFqkqxm+l7d4DEnhQyOI=', u'x-amz-request-id': u'AF670CB18044CF20'}, u'awsRegion': u'ap-northeast-1', u'eventName': u'ObjectCreated:Put', u'userIdentity': {u'principalId': u'AWS:AROAI2AVVYPD5HCMVJROA:campi-dev'}, u'eventSource': u'aws:s3'}]}
[1479966175271] need more than 1 value to unpack: ValueError
Traceback (most recent call last):
  File "/var/task/handler.py", line 480, in lambda_handler
    return LambdaHandler.lambda_handler(event, context)
  File "/var/task/handler.py", line 192, in lambda_handler
    return handler.handler(event, context)
  File "/var/task/handler.py", line 352, in handler
    app_function = self.import_module_and_get_function(whole_function)
  File "/var/task/handler.py", line 182, in import_module_and_get_function
    module, function = whole_function.rsplit('.', 1)
ValueError: need more than 1 value to unpack

I feel this might have something to do with the way that zappa is trying to read the function from the module. Here is the function in question, and my zappa config:
**Function:**

`def handler(event, context):
    for record in event['Records']:
        bucket = record['s3']['bucket']['name']
        key = record['s3']['object']['key']
        # Take the time stamp from the key
        p = re.compile('\d{5,}')
        time = int(p.findall(key)[0])
        piID = (key.split('/'))[1]
        response = TABLE_CAMERAKEYS.put_item(
            Item={
                'piID': piID,
                'time': time,
                'image_key': key,
            }
        )
    return 200`

**Zappa config**
> {
    "dev": {
        "s3_bucket": "CHANGEDFORPRIVACY",
        "aws_region": "ap-northeast-1",
        "app_function": "camera.app",
        "project_name": "s3todynamo",
        "use_apigateway": true,
        "api_key_required": false,
        "manage_roles": true,
        "keep_warm": false,
        "debug": true,
        "lambda_description": "add value to s3 when camera image added", 
        "events": [
            {
               "function": "camera.handler",
               "event_source": {
                   "arn": "arn:aws:s3:::CHANGEDFORPRIVACY",
                   "events": [
                        "s3:ObjectCreated:*"
                ]
            }
        }],   
    }
}

Any idea what the issue might be? I'm out of ideas.

Thanks.

**Comment by Miserlou** [comment] 2016-11-24 13:43
Dupe of https://github.com/Miserlou/Zappa/issues/473, PR already submitted, which I will review, merge and publish today.

**Comment by Miserlou** [comment] 2016-11-24 15:07
Fixed in 0.29.2

**Closed by Miserlou** 2016-11-24 15:07 UTC
Labels: duplicate
