### ISSUE TITLE
zappa update should not create new duplicate keep_warm event

### ISSUE THREAD

**Issue by kienpham2000** [Miserlou/Zappa#127] opened 2016-06-01 18:10 UTC
I have my "keep_warm": true, in the config file but whenever I zappa update dev, it creates new keep warm event showing up in the Event Sources UI.

**Comment by Miserlou** [comment] 2016-06-02 19:04
Duplicate of https://github.com/Miserlou/Zappa/issues/101 - resolved, fix should be pushed today.

**Closed by Miserlou** 2016-06-02 19:04 UTC
