### ISSUE TITLE
AttributeError: 'module' has no attribute 'get_installed_distributions'

### ISSUE THREAD

**Issue by matinde** [Miserlou/Zappa#1471] opened 2018-04-07 15:57 UTC
## Context
When deploying a project with "zappa deploy [project-name]" I get the error: **AttributeError: 'module' has no attribute 'get_installed_distributions'**

I honestly do not know what is wrong or what I am missing. Any help please provide simple step by step instructions to solve this. 
![zappa error](https://user-images.githubusercontent.com/18006636/38457147-6c8eba2c-3a95-11e8-8e16-62ee366b52b0.png)

>

**Comment by varunbalupuri** [comment] 2018-04-07 17:35
Upgrading virtualenv fixed this for me.

`sudo pip install virtualenv --upgrade`

Please try that and see if the problem is fixed.

**Comment by matinde** [comment] 2018-04-08 05:54
Thanks, but I did upgrade virtualenv but it didn't work. I still get the error message.

**Comment by paulclarkaranz** [comment] 2018-04-08 22:50
You probably have a newer pip, they made changes to their ~~public api~~ top level functions recently. Try downgrading with `pip install pip==9.0.1` or to 8.1.2.

**Comment by disambiguator** [comment] 2018-04-09 20:59
I also got this to work by running `sudo pip3 install virtualenv --upgrade`. Thank you for your response @varunbalupuri !

**Comment by scoates** [comment] 2018-04-09 21:19
Closing. Comment and we'll reopen if it's a Zappa problem.

**Closed by scoates** 2018-04-09 21:19 UTC
Labels: non-bug

**Comment by neotheicebird** [comment] 2018-04-15 20:30
AttributeError: 'pip' has no attribute 'get_installed_distributions'

For pip == 10.0.0

You can downgrade pip to >= 9.0.0 to fix this

**Comment by oxbits** [comment] 2018-04-15 20:59
Thank you @neotheicebird!  I downgraded and it fixed the issue for me.

**Comment by wobeng** [comment] 2018-04-18 22:31
@scoates how come you don't consider this as a Zappa issue? adjusting to pip is better than downgrading to Zappa

**Comment by paulclarkaranz** [comment] 2018-04-18 22:40
There are already two open issues about adapting to pip's new api (aka subprocess): #1478 #1446

**Comment by shivampaw** [comment] 2018-04-25 19:33
I'm running into this issue. I tried downgrading pip and can confirm it is done because pip --version returns 9.0.3 but i still get the same error from zappa

**Comment by disambiguator** [comment] 2018-04-25 22:33
@shivampaw `sudo pip3 install virtualenv --upgrade`

**Comment by shivampaw** [comment] 2018-04-25 22:40
nvm, turns out rebooting does fix problems...

**Comment by naamancampbell** [comment] 2018-04-27 23:15
Installing pip==9.0.3 after activating the virtualenv works for me:

```
pip install virtualenv
virtualenv venv
. ./venv/bin/activate
pip install pip==9.0.3
```

**Comment by NathanLawrence** [comment] 2018-05-09 15:19
I know this issue is closed, but this is obviously still ongoing, and I'd love if we could find a way to patch it up. Anyone clear on the mechanics of what's going wrong here? I'm happy to get my hands dirty, but only if I know what I'm doing.

**Comment by scoates** [comment] 2018-05-09 15:27
My comment above was indeed in error, but the root of this problem is the pip changes, I believe, now.

#1478 + #1481

**Comment by jasweet** [comment] 2018-05-13 06:26
Hello all.

The prob is def pip. Broken in 10.x.

However, depending on your environment, you may need to downgrade pip or pip3. For my fedora box it was pip and my windows machine was pip3. Just depends which interpreter you're using for the problem file/package.

**Comment by Shaun1** [comment] 2018-05-14 19:46
Downgrading to pip 9.0.3 (both globally and in virutualenv) worked for me too. But this sounds like a Zappa issue, not a pip issue.

**Comment by jasweet** [comment] 2018-05-15 20:16
True. It’s that pip updated location/structure of some internal resources. Other libraries that leverage resources internal to pip can become broken when pip makes changes.

**Comment by raveenb** [comment] 2018-05-20 18:02
I too have had this issue, downgrading pip in the virtualenv resolved this

**Comment by WonderMr** [comment] 2018-05-25 06:38
For pip 10 use `from pip._internal.utils.misc import get_installed_distributions`

**Comment by MoBattah** [comment] 2018-05-31 20:10
Breaks Zappa. None of the above suggestions worked for me.

**Comment by NathanLawrence** [comment] 2018-06-07 16:45
@MoBattah Exact same issue, yet you couldn't get it to find the APIs even when you're running the old version? Mind posting up prints of `pip -V` inside and outside your virtualenvs so we can troubleshoot?

**Comment by fergyfresh** [comment] 2018-06-13 21:52
This 100% doesn't work with `pip==10.0.1` and definitely does work with pip==9.0.

![image](https://user-images.githubusercontent.com/9665592/41380276-83f3bd6c-6f32-11e8-8d43-cdd9cfcbfdaa.png)

**Comment by ufmayer** [comment] 2018-08-13 17:43
Following WonderMr's post, this worked for me:
`
if pip.__version__ >= "10.0.0":
    from pip._internal.utils.misc import get_installed_distributions
else:
    from pip import get_installed_distributions
`

**Comment by nabaz** [comment] 2018-10-03 19:37
downgrade pip and remove slim-handler if you have that option set also

**Comment by krikru** [comment] 2019-01-12 01:09
Try `pip list`.

**Comment by ryanjdillon** [comment] 2019-01-24 13:31
I just encountered this as well. According to [this issue](https://github.com/pypa/pip/issues/5243), zappa `core.py` should be updated to use `pkg_resources.working_set`.

```python
import pkg_resources
pkg_resources.working_set
```

**Comment by johnyoonh** [comment] 2019-09-06 01:07
For me it was setting the runtime properly in zappa_settings.json
