### ISSUE TITLE
400 Bad request on anything except for GET

### ISSUE THREAD

**Issue by 7wonders** [Miserlou/Zappa#47] opened 2016-03-31 01:27 UTC
If i try a POST or DELETE i end up with a 400. Any ideas? Its a pretty straightforward flask app

```
Traceback (most recent call last): File "/var/task/handler.py", line 137, in lambda_handler return LambdaHandler.lambda_handler(event, context) File "/var/task/handler.py", line 51, in lambda_handler return cls().handler(event, context) File "/var/task/handler.py", line 132, in handler raise Exception(exception) Exception: 
<!DOCTYPE html>400<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>400 Bad Request</title>
<h1>Bad Request</h1>
<p>The browser (or proxy) sent a request that this server could not understand.</p>
```

**Comment by Miserlou** [comment] 2016-03-31 17:59
Not quite sure what's going on there, but I don't think it's related to the type of request.

For instance, in a test Flask app with the current Zappa version in PyPi: https://vna1tr18s7.execute-api.us-east-1.amazonaws.com/test/post

Seems to work fine.

Could it be something else about the function? Do you see anything else if you do 'zappa tail ((your env))'

**Comment by Miserlou** [comment] 2016-03-31 19:39
Other things that might help me debug - 

Where was your forms action pointing at? If you point to "/" on the server without using a domain, you'll have a problem there.
What was the content-type of the POST message, and of the response?

**Comment by Miserlou** [comment] 2016-03-31 20:10
Seems to work fine on domains as well: https://flask.gun.io/post

**Comment by Miserlou** [comment] 2016-04-01 19:32
Any updates on this @7wonders? I'd love to fix this if there is a bug in the code, but unfortunately I'm unable to reproduce it, so I can't fix it.

**Comment by Miserlou** [comment] 2016-04-01 21:01
I just pushed 0.16.0 which may help to debug this.

**Comment by Miserlou** [comment] 2016-04-07 20:38
I'm going to close this if I can't get any more information, unfortunately. Feel free to open if you wan to provide more information.

**Closed by Miserlou** 2016-04-07 20:38 UTC
